### ISSUE TITLE
补丁无法生效

### ISSUE THREAD

**Issue by TXT2GAM** [CSGA-KPX/2236-Translate#11]
steam版，已替换`Windows\`目录下的补丁文件`2236.scenarios.asset`；并删除了`Chloro_2236 A_D_ -Universal Edition-`整个缓存文件夹。
启动游戏后依旧是英文。并且观察到补丁文件`2236.scenarios.asset`并未被再次覆盖。

**Comment by CSGA-KPX** [comment]
我这边无法复现，检查了一下发现游戏会生成多个名字和路径接近的文件夹。 

1. `AppData\LocalLow\Unity\Chloro_2236 A_D_ -Universal Edition-` 缓存文件夹 
2. `AppData\LocalLow\Chloro\2236 A.D. -Universal Edition-` 存档 
3. `AppData\Local\Temp\Chloro\2236 A_D_ -Universal Edition-` 临时文件 

请检查删除的文件夹路径，如果还是不行可以全删试试，3可能也对缓存有贡献。


考虑到 #10 内dlsite版也生效了应该没有特殊的处理机制。如果还不行我换一台机子看看情况

**Comment by CSGA-KPX** [comment]
我这边没有生成过WebPlayer这个文件夹，查了一下Unity Web Player已经被弃用了很多年了不知道是怎么被激活的。

我这边的缓存目录是这样的，在Win11和另一台Win10上都没有生成过WebPlayer文件夹：
![Snipaste_2023-10-03_09-58-42](https://github.com/CSGA-KPX/2236-Translate/assets/2347318/c80af79e-7b25-4d15-93c1-2deec861fa4b)

根据 [这篇内容](https://blog.csdn.net/shuihuyunyun/article/details/53996173) 你可能需要删掉整个WebPlayer然后再清除IE缓存。建议手动操作不要使用他提供的bat文件

**Comment by HinemoSusutsu** [comment]
dlsite版 问题同上 不知道有什么解决办法 也是会生成WebPlayers 整个文件夹删除使用补丁仍旧无效

**Comment by CSGA-KPX** [comment]
不明，我这边三台不同的Win11/10都无法完全无法触发出WebPlayer。其它issue中dlsite版本也能正常运行。

看看清理下系统是不是别的游戏带了WebPlayer环境吧…………太诡异了

**Comment by Okny0** [comment]
我玩的是网上找来的盗版，R18版本，应该是dlsite版，遇到了同样的问题。
为了防止原因出在其他Unity游戏上，我更换了一台工作用电脑，确保打开2236之前AppData\LocalLow\目录下没有Unity文件夹，可结果还是生成了WebPlayer。
过几天等Steam冬促我会买个Steam版试试问题是否会复现。

**Comment by CSGA-KPX** [comment]
我在网上下载到了一个国内打包，主程序 `2236 A.D. -Universal Edition-.exe` 修改日期2018年8月20日，md5码为76dea23368a0cd93fe971a465a337814的版本，目前只有该版本生成了WebPlayer文件。仅供参考。

~~您可能是盗版受害者~~

**Comment by Okny0** [comment]
虽然不是史低价格，但今天还是购入了Steam版，打上补丁之后英文被替换为了中文，也没有生成WebPlayer文件夹。
另外我玩的盗版主程序为2236 A.D. -R18 Edition-，并非-Universal Edition-，暂且不知道是从哪里搞来的，总之感谢你的回复和汉化，我这边问题已经解决了。
