### ISSUE TITLE
亲爱的作者，您好，我在使用本补丁时，卡在了第三步，我无法找到'2236utils.exe'请您指点一下

### ISSUE THREAD

**Issue by hanye2432** [CSGA-KPX/2236-Translate#21]

**Comment by CSGA-KPX** [comment]
单纯使用补丁的话。去Release页面下载对应补丁然后按照[补丁使用说明](https://github.com/CSGA-KPX/2236-Translate/blob/master/Docs/%E8%A1%A5%E4%B8%81%E4%BD%BF%E7%94%A8.md)替换文件清缓存

~~好久没管了我整理下说明~~

**Comment by CSGA-KPX** [comment]
请问有后续进展吗？

**Comment by hanye2432** [comment]
已经直接替换进行游玩了，感谢作者大大的指点Orz
